from __future__ import annotations


RESOLUTIONS = {
    "head_shot": (1024, 1536),
    "half_body": (1024, 1536),
    "full_body": (1024, 1536),
}

MAX_POSITIVE_PROMPT_LENGTH = 99999  # 不再限制提示词长度
PROMPT_PART_ORDER = (
    "director_plan",
    "camera",
    "character",
    "outfit",
    "pose_expression",
    "scene_light",
    "quality",
)
VISIBLE_PROMPT_PARTS = set(PROMPT_PART_ORDER)
TRIMMABLE_PARTS = ("quality", "scene_light", "outfit", "camera", "pose_expression")
WHITE_EDGE_REPLACEMENTS = (
    ("纯白背景", "浅彩背景"),
    ("纯白侧边", "彩色环境侧边"),
    ("空白侧边", "环境色侧边"),
    ("白色边框", "自然环境边缘"),
    ("白边", "环境边缘"),
    ("白底", "浅彩背景"),
    ("黑边", "场景内容边缘"),
    ("黑色侧边", "横向场景内容"),
    ("暗色侧边", "横向场景内容"),
    ("左右环境空间", "横向场景内容铺满画面"),
    ("左右边距保留外轮廓", "横向场景内容铺满画面并保留外轮廓"),
    ("左右边距", "横向场景内容"),
    ("四周留环境边距", "四周都有真实场景内容"),
    ("四周留床面或地面边距", "四周都有床面或地面内容"),
    ("四周边距", "四周场景内容"),
)


FEEDBACK_TAG_RULES = {
    "active_smile": ("笑", "微笑", "大笑", "俏皮", "坏笑", "灿烂", "得意", "怪罪"),
    "avoid_flat_face": ("冷淡", "平静", "淡淡", "含蓄", "礼貌", "几乎看不见"),
    "full_body_foot_anchor": ("脚下", "地面", "沙面", "草地", "瓷砖", "甲板", "路面", "站点"),
    "forced_perspective": ("近大远小", "强透视", "视觉路径"),
    "vivid_color": ("高饱和", "鲜艳", "彩色", "湖蓝", "珊瑚粉", "柠檬黄", "薄荷绿", "桃橙", "玫瑰粉"),
    "red_lip_risk": ("红唇", "深红", "酒红", "浆果", "暗红", "厚唇", "丰唇"),
    "white_padding_risk": ("白边", "留白", "空白", "纯白", "白色边框", "黑边", "黑色侧边", "暗色侧边", "左右边距", "左右环境空间"),
}

QUALITY_BY_SCALE = {
    "normal": "商业写真级自然光影，肤色真实不过曝，清晰镜头景深，暗部有层次",
    "bold": "高级私房写真调色，肤质细腻但保留真实纹理，光影有层次，高光不过曝",
    "bold_no_outfit": "高级私房写真调色，肤质细腻但保留真实纹理，光影有层次，高光不过曝",
    "nsfw": "高级私房写真调色，肤质细腻保留真实纹理，光影有层次，高光不过曝，sharp focus, detailed skin, natural anatomy",
}
QUALITY_SUFFIX = QUALITY_BY_SCALE["bold"]  # fallback

# 一档(normal)画质池：按镜头细分，加入焦段/光圈/虚化/色调/胶片/颗粒/构图，
# 解决原先「时尚人像摄影…」全档复读的模板句问题。
QUALITY_OPTIONS_BY_SHOT = {
    "head_shot": [
        "85mm 中长焦特写，f/1.8 浅景深，背景虚化成柔和色块，柯达 Portra 400 暖调，高光柔润，颗粒细腻",
        "135mm 压缩感特写，背景奶油化散景，富士 Pro 400H 冷调，肤色通透，低反差",
        "50mm 自然视角近景，窗边柔光，浅景深保留环境色温，轻微胶片颗粒",
        "100mm 微距质感特写，皮肤纹理清晰，侧逆光勾出轮廓，暖色胶片感",
        "90mm 人像特写，f/2 虚化背景，伦勃朗式侧光，肤色柔和，暗部干净",
    ],
    "upper_body": [
        "85mm 标准人像焦段，f/2 虚化背景，日光胶片色调，明暗过渡柔顺",
        "105mm 中长焦，背景压暗成色块，柯达 Gold 暖调，自然肤色",
        "70mm 环境人像，保留部分场景纵深，柔和散景，低饱和暖色",
        "80mm 半身特写，f/2.2 浅景深，轮廓光描边，富士业务卷冷调",
    ],
    "half_body": [
        "85mm 半身人像，f/2.8 适度景深，环境虚化但保留层次，电影感暖调",
        "50mm 环境叙事焦段，前景轻微虚化，柔和日光，自然胶片颗粒",
        "135mm 压缩背景，人物从暖色环境里浮出，柯达 Portra 色调",
        "100mm 半身构图，f/2.5 虚化，侧光塑形，低反差奶油调",
    ],
    "large_half_body": [
        "85mm 大半身构图，f/2.5 景深，腿部线条柔化，暖色散景",
        "50mm 带环境叙事，身体曲线在柔光中展开，低反差奶油调",
        "105mm 中长焦，背景虚化成色块，人物从环境里浮出，暖调胶片",
    ],
    "full_body": [
        "50mm 全身环境人像，f/4 较实景深，保留场景纵深，自然日光色调",
        "35mm 略广角带环境，人物嵌入场景，柔和散景，清新胶片感",
        "85mm 压缩全身，背景虚化成色块，暖调胶片，肢体线条流畅",
        "45mm 环境叙事焦段，f/3.5 适度景深，人物与场景平衡，日光通透",
    ],
}

NEGATIVE_PROMPT_RULES = {
    "base_quality": (
        "low quality",
        "blurry",
        "bad anatomy",
        "extra fingers",
        "missing fingers",
        "distorted face",
        "deformed body",
        "duplicated limbs",
        "text",
        "watermark",
        "logo",
        "latex clothing",
        "PVC clothing",
        "rubber clothing",
        "plastic clothing",
        "vinyl clothing",
        "glossy plastic fabric",
        "shiny latex",
    ),
    "lips_makeup": (
        "red lipstick",
        "bright red lips",
        "dark red lips",
        "burgundy lips",
        "wine-red lips",
        "crimson lips",
        "dark lipstick",
        "black lipstick",
        "over-saturated lip color",
        "lip tint",
        "colored lipstick",
        "obvious lipstick",
        "unnatural lip color",
        "plump lips",
        "full lips",
        "thick lips",
        "overlined lips",
        "overfilled lips",
        "swollen lips",
        "lip filler",
        "heavy smoky makeup",
        "glitter eye makeup",
        "sparkly eyeshadow",
        "shimmer eyeshadow",
        "metallic eyeshadow",
        "rhinestones around eyes",
        "crystal stickers around eyes",
        "sequins on eyelids",
        "face gems",
        "eye gems",
        "wide grin",
        "big grin",
        "toothy smile",
        "open mouth smile",
        "exaggerated smile",
        "creepy smile",
        "unnatural smile",
        "teeth showing",
        "large red blush",
        "flushed red face",
    ),
    "canvas_padding": (
        "white border",
        "black border",
        "blank side margins",
        "white side bars",
        "black side bars",
        "dark side bars",
        "pillarbox",
        "letterbox",
        "empty white background",
        "empty black background",
        "white padding",
        "black padding",
        "dark padding",
        "canvas padding",
        "solid white sides",
        "solid black sides",
        "plain white side background",
        "plain black side background",
        "vertical photo on wide canvas",
        "portrait image centered on landscape canvas",
        "unused canvas sides",
        "empty dark side background",
        "black pillarbox",
        "dark pillarbox",
    ),
    "landscape_mismatch": (
        "portrait crop inside landscape canvas",
        "vertical body centered with side bars",
        "standing portrait composition on wide canvas",
        "narrow portrait image in wide frame",
        "empty left and right sides",
    ),
    "portrait_mismatch": (
        "horizontal body cropped in vertical frame",
        "sideways landscape composition in portrait frame",
        "missing head",
        "missing feet",
    ),
    "shot_scope_head": (
        "full body",
        "half body",
        "legs",
        "feet",
        "shoes",
        "standing pose",
        "sitting pose",
    ),
    "shot_scope_upper": (
        "legs",
        "feet",
        "shoes",
        "full body",
        "lower body",
        "navel",
    ),
    "shot_scope_half": (
        "feet",
        "shoes",
        "lower legs",
        "full body",
        "full figure",
    ),
    "full_body_integrity": (
        "cropped feet",
        "missing feet",
        "cropped head",
        "missing head",
        "cut off legs",
        "short distorted legs",
        "compressed body proportions",
    ),
    "legal_safety": (
        "explicit sexual act",
        "exposed genitals",
    ),
    "nsfw_amateur_tone": (
        "amateur photography",
        "home video",
        "webcam quality",
        "clinical lighting",
        "flat lighting",
        "sanitary",
        "sterile",
        "overexposed",
        "washed out",
    ),
}

PART_LENGTH_BUDGETS = {
    "camera": 74,
    "character": 200,
    "makeup": 74,
    "outfit": 130,
    "pose_expression": 220,
    "scene_light": 210,
    "quality": 130,
}

NSFW_PART_LENGTH_BUDGETS = {
    "camera": 90,
    "character": 180,
    "makeup": 60,
    "outfit": 0,
    "pose_expression": 160,
    "scene_light": 140,
    "quality": 120,
}

SHOT_ALIASES = {
    "": "full_body",
    "random": "random",
    "随机": "random",
    "随机镜头": "random",
    "full": "full_body",
    "full_body": "full_body",
    "全身": "full_body",
    "全身像": "full_body",
    "全身镜头": "full_body",
    "half": "half_body",
    "half_body": "half_body",
    "半身": "half_body",
    "半身像": "half_body",
    "半身镜头": "half_body",
    "大腿以上": "half_body",
    "大腿以上镜头": "half_body",
    "head": "head_shot",
    "head_shot": "head_shot",
    "头部": "head_shot",
    "头部镜头": "head_shot",
    "肩膀及以上": "head_shot",
    "肩膀及以上镜头": "head_shot",
    "肩部以上": "head_shot",
    "肩部以上镜头": "head_shot",
    "face": "head_shot",
    "face_closeup": "head_shot",
    "全身构图": "full_body",
    "全身构图镜头": "full_body",
    "全身像镜头": "full_body",
    "半身像镜头": "half_body",
    "大腿及以上": "half_body",
    "大腿及以上半身": "half_body",
    "大腿及以上半身像": "half_body",
    "脸部特写": "head_shot",
    "面部特写": "head_shot",
    "肩部以上特写": "head_shot",
    "脸部特写镜头": "head_shot",
    "面部特写镜头": "head_shot",
}

SCALE_ALIASES = {
    "一档": "normal",
    "二档": "bold",
    "三档": "bold_no_outfit",
    "四档": "nsfw",
    "普通": "normal",
    "大胆": "bold",
    "NSFW": "nsfw",
    "normal": "normal",
    "bold": "bold",
    "bold_no_outfit": "bold_no_outfit",
    "no_outfit": "bold_no_outfit",
    "d": "bold_no_outfit",
    "D": "bold_no_outfit",
    "nsfw": "nsfw",
}

ERA_ALIASES = {
    "": "modern",
    "modern": "modern",
    "现代": "modern",
    "現代": "modern",
    "古装": "ancient",
    "古代": "ancient",
    "ancient": "ancient",
    "costume": "ancient",
}

ANCIENT_OUTFIT_MARKERS = (
    "古装",
    "古典",
    "汉服",
    "中式",
    "盘扣",
    "斜襟",
    "唐制",
    "宋制",
    "明制",
    "敦煌",
    "胡姬",
    "侠女",
    "宫廷",
    "旗装",
    "马面裙",
    "襦裙",
    "褙子",
    "披帛",
    "花魁",
    "夜宴",
    "青绿山水",
    "苗疆",
    "民国",
    "银饰",
    "步摇",
    "云头鞋",
    "绣鞋",
    "云肩",
)
ANCIENT_SCENE_MARKERS = (
    "古代",
    "中式",
    "宫苑",
    "宫廷",
    "屏风",
    "花窗",
    "竹帘",
    "木格窗",
    "青瓦",
    "寝殿",
    "廊下",
    "书房",
    "卷轴",
    "香炉",
    "烛台",
    "木案",
    "铜镜",
    "宫灯",
    "纱帐",
    "敦煌",
    "宫墙",
    "琉璃瓦",
    "水榭",
    "茶楼",
    "山寺",
    "回廊",
    "朱栏",
    "船舫",
    "雕花窗",
    "温泉",
    "石池",
)

FORBIDDEN_BY_SHOT = {
    "head_shot": (
        "胸", "乳", "完整腰", "腰", "肚脐", "腹", "臀", "胯", "大腿", "小腿", "膝", "腿", "脚", "高跟", "鞋", "丝袜", "裸足", "裙", "全身", "半身", "站立", "坐姿", "跪", "躺",
    ),
    "half_body": (
        "全身", "完整身形", "脚", "脚趾", "脚部", "裸足", "高跟", "鞋", "从头到脚", "头顶到脚",
    ),
    "full_body": (),
}

LIP_COLOR_CONSTRAINT = "纤薄原生唇形，透明无色水光，浅粉自然唇色"
HEAD_SHOT_FRAMING_CONSTRAINT = "头部镜头，肩膀及以上入镜，头顶完整，脸部、发丝、颈部和双肩线条清楚，画面下缘停在肩膀下缘"
HALF_BODY_FRAMING_CONSTRAINT = "半身镜头，大腿以上入镜，头部、脸部、肩颈、胸部、腰臀、大腿和手部动作清楚，画面下缘停在大腿到膝部之间"
FULL_BODY_PORTRAIT_FRAMING_CONSTRAINT = "全身镜头，人物从头顶到脚部完整入镜，手臂、腿部、脚部落点和姿势外轮廓都清楚"
