from __future__ import annotations


RESOLUTIONS = {
    "head_shot": (1024, 1536),
    "half_body": (1024, 1536),
    "full_body": (1024, 1536),
}

PROMPT_PART_ORDER = (
    "director_plan",
    "camera",
    "character",
    "outfit",
    "pose_expression",
    "scene_light",
    "quality",
)
VISIBLE_PROMPT_PARTS = set(PROMPT_PART_ORDER)
WHITE_EDGE_REPLACEMENTS = (
    ("纯白背景", "浅彩背景"),
    ("纯白侧边", "彩色环境侧边"),
    ("空白侧边", "环境色侧边"),
    ("白色边框", "自然环境边缘"),
    ("白边", "环境边缘"),
    ("黑边", "场景内容边缘"),
    ("黑色侧边", "横向场景内容"),
    ("暗色侧边", "横向场景内容"),
    ("左右环境空间", "横向场景内容铺满画面"),
    ("左右边距保留外轮廓", "横向场景内容铺满画面并保留外轮廓"),
    ("左右边距", "横向场景内容"),
    ("四周留环境边距", "四周都有真实场景内容"),
    ("四周留床面或地面边距", "四周都有床面或地面内容"),
    ("四周边距", "四周场景内容"),
)


FEEDBACK_TAG_RULES = {
    "active_smile": ("笑", "微笑", "大笑", "俏皮", "坏笑", "灿烂", "得意", "怪罪"),
    "avoid_flat_face": ("冷淡", "平静", "淡淡", "含蓄", "礼貌", "几乎看不见"),
    "full_body_foot_anchor": ("脚下", "地面", "沙面", "草地", "瓷砖", "甲板", "路面", "站点"),
    "forced_perspective": ("近大远小", "强透视", "视觉路径"),
    "vivid_color": ("高饱和", "鲜艳", "彩色", "湖蓝", "珊瑚粉", "柠檬黄", "薄荷绿", "桃橙", "玫瑰粉"),
    "red_lip_risk": ("红唇", "深红", "酒红", "浆果", "暗红", "厚唇", "丰唇"),
    "white_padding_risk": ("白边", "留白", "空白", "纯白", "白色边框", "黑边", "黑色侧边", "暗色侧边", "左右边距", "左右环境空间"),
}

QUALITY_BY_SCALE = {
    "normal": "商业写真级自然光影，肤色真实不过曝，清晰镜头景深，暗部有层次",
    "bold": "高级私房写真，肤质细腻并保留真实纹理，光影有层次，高光不过曝",
    "bold_no_outfit": "高级私房写真，肤质细腻并保留真实纹理，光影有层次，高光不过曝",
    "nsfw": "高级私房写真调色，肤质细腻保留真实纹理，光影有层次，高光不过曝，sharp focus, detailed skin, natural anatomy",
}
QUALITY_SUFFIX = QUALITY_BY_SCALE["bold"]  # fallback

NEGATIVE_PROMPT_RULES = {
    "base_quality": (
        "low quality",
        "blurry",
        "bad anatomy",
        "extra fingers",
        "missing fingers",
        "distorted face",
        "deformed body",
        "duplicated limbs",
        "text",
        "watermark",
        "logo",
        "latex clothing",
        "PVC clothing",
        "rubber clothing",
        "plastic clothing",
        "vinyl clothing",
        "glossy plastic fabric",
        "shiny latex",
    ),
    "lips_makeup": (
        "red lipstick",
        "bright red lips",
        "dark red lips",
        "burgundy lips",
        "wine-red lips",
        "crimson lips",
        "dark lipstick",
        "black lipstick",
        "over-saturated lip color",
        "lip tint",
        "colored lipstick",
        "obvious lipstick",
        "unnatural lip color",
        "plump lips",
        "full lips",
        "thick lips",
        "overlined lips",
        "overfilled lips",
        "swollen lips",
        "lip filler",
        "heavy smoky makeup",
        "glitter eye makeup",
        "sparkly eyeshadow",
        "shimmer eyeshadow",
        "metallic eyeshadow",
        "rhinestones around eyes",
        "crystal stickers around eyes",
        "sequins on eyelids",
        "face gems",
        "eye gems",
        "wide grin",
        "big grin",
        "toothy smile",
        "open mouth smile",
        "exaggerated smile",
        "creepy smile",
        "unnatural smile",
        "teeth showing",
        "large red blush",
        "flushed red face",
    ),
    "canvas_padding": (
        "white border",
        "black border",
        "blank side margins",
        "white side bars",
        "black side bars",
        "dark side bars",
        "pillarbox",
        "letterbox",
        "empty white background",
        "empty black background",
        "white padding",
        "black padding",
        "dark padding",
        "canvas padding",
        "solid white sides",
        "solid black sides",
        "plain white side background",
        "plain black side background",
        "vertical photo on wide canvas",
        "portrait image centered on landscape canvas",
        "unused canvas sides",
        "empty dark side background",
        "black pillarbox",
        "dark pillarbox",
    ),
    "landscape_mismatch": (
        "portrait crop inside landscape canvas",
        "vertical body centered with side bars",
        "standing portrait composition on wide canvas",
        "narrow portrait image in wide frame",
        "empty left and right sides",
    ),
    "portrait_mismatch": (
        "horizontal body cropped in vertical frame",
        "sideways landscape composition in portrait frame",
        "missing head",
        "missing feet",
    ),
    "shot_scope_head": (
        "full body",
        "half body",
        "legs",
        "feet",
        "shoes",
        "standing pose",
        "sitting pose",
    ),
    "shot_scope_upper": (
        "legs",
        "feet",
        "shoes",
        "full body",
        "lower body",
        "navel",
    ),
    "shot_scope_half": (
        "feet",
        "shoes",
        "lower legs",
        "full body",
        "full figure",
    ),
    "full_body_integrity": (
        "cropped feet",
        "missing feet",
        "cropped head",
        "missing head",
        "cut off legs",
        "short distorted legs",
        "compressed body proportions",
    ),
    "legal_safety": (
        "explicit sexual act",
        "exposed genitals",
    ),
    "nsfw_amateur_tone": (
        "amateur photography",
        "home video",
        "webcam quality",
        "clinical lighting",
        "flat lighting",
        "sanitary",
        "sterile",
        "overexposed",
        "washed out",
    ),
}

SHOT_ALIASES = {
    "": "full_body",
    "random": "random",
    "随机": "random",
    "随机镜头": "random",
    "full": "full_body",
    "full_body": "full_body",
    "全身": "full_body",
    "全身像": "full_body",
    "全身镜头": "full_body",
    "half": "half_body",
    "half_body": "half_body",
    "半身": "half_body",
    "半身像": "half_body",
    "半身镜头": "half_body",
    "大腿以上": "half_body",
    "大腿以上镜头": "half_body",
    "head": "head_shot",
    "head_shot": "head_shot",
    "头部": "head_shot",
    "头部镜头": "head_shot",
    "肩膀及以上": "head_shot",
    "肩膀及以上镜头": "head_shot",
    "肩部以上": "head_shot",
    "肩部以上镜头": "head_shot",
    "face": "head_shot",
    "face_closeup": "head_shot",
    "全身构图": "full_body",
    "全身构图镜头": "full_body",
    "全身像镜头": "full_body",
    "半身像镜头": "half_body",
    "大腿及以上": "half_body",
    "大腿及以上半身": "half_body",
    "大腿及以上半身像": "half_body",
    "脸部特写": "head_shot",
    "面部特写": "head_shot",
    "肩部以上特写": "head_shot",
    "脸部特写镜头": "head_shot",
    "面部特写镜头": "head_shot",
}

SCALE_ALIASES = {
    "一档": "normal",
    "二档": "bold",
    "三档": "bold_no_outfit",
    "四档": "nsfw",
    "普通": "normal",
    "大胆": "bold",
    "NSFW": "nsfw",
    "normal": "normal",
    "bold": "bold",
    "bold_no_outfit": "bold_no_outfit",
    "no_outfit": "bold_no_outfit",
    "d": "bold_no_outfit",
    "D": "bold_no_outfit",
    "nsfw": "nsfw",
}


ANCIENT_SCENE_MARKERS = (
    "古代",
    "中式",
    "宫苑",
    "宫廷",
    "屏风",
    "花窗",
    "竹帘",
    "木格窗",
    "青瓦",
    "寝殿",
    "廊下",
    "书房",
    "卷轴",
    "香炉",
    "烛台",
    "木案",
    "铜镜",
    "宫灯",
    "纱帐",
    "敦煌",
    "宫墙",
    "琉璃瓦",
    "水榭",
    "茶楼",
    "山寺",
    "回廊",
    "朱栏",
    "船舫",
    "雕花窗",
    "温泉",
    "石池",
)

FORBIDDEN_BY_SHOT = {
    "head_shot": (
        "胸", "乳", "完整腰", "腰", "肚脐", "腹", "臀", "胯", "大腿", "小腿", "膝", "腿", "脚", "高跟", "鞋", "丝袜", "裸足", "裙", "全身", "半身", "站立", "坐姿", "跪", "躺",
    ),
    "half_body": (
        "全身", "完整身形", "脚", "脚趾", "脚部", "裸足", "高跟", "鞋", "从头到脚", "头顶到脚",
    ),
    "full_body": (),
}

