from __future__ import annotations

import argparse
import pprint
from pathlib import Path

from prompt_excel_io import read_workbook


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = ROOT / "data" / "prompt_pools.xlsx"
DEFAULT_OUTPUT = ROOT / "prompt_data_generated.py"

CONSTANT_NAMES = ("QUALITY_SUFFIX", "NEGATIVE_PROMPT")
POOL_NAMES = (
    "CAMERA_OPTIONS",
    "CHARACTER_IDENTITY_BY_SHOT",
    "MAKEUP_OPTIONS",
    "HAIR_STATE_OPTIONS",
    "OUTFIT_OPTIONS",
    "POSE_EXPRESSION_OPTIONS",
    "SCENE_LIGHT_OPTIONS",
    "landscape_camera_options",
    "landscape_pose_expression_options",
)
SCALE_SHOT_POOLS = {"OUTFIT_OPTIONS", "POSE_EXPRESSION_OPTIONS", "SCENE_LIGHT_OPTIONS", "landscape_pose_expression_options"}
SHOT_POOLS = {"CAMERA_OPTIONS", "CHARACTER_IDENTITY_BY_SHOT", "landscape_camera_options"}
SCALE_POOLS = {"MAKEUP_OPTIONS", "HAIR_STATE_OPTIONS"}
SCENE_LIGHT_GROUP_PREFIX = "场景包:"
SCENE_LIGHT_GROUPS = ("室内", "室外", "野外")


def row_dicts(rows: list[list[str]]) -> list[dict[str, str]]:
    if not rows:
        return []
    headers = [cell.strip() for cell in rows[0]]
    result = []
    for row in rows[1:]:
        item = {header: row[index].strip() if index < len(row) else "" for index, header in enumerate(headers)}
        if any(item.values()):
            result.append(item)
    return result


def enabled(value: str) -> bool:
    return value.strip().lower() not in {"0", "false", "no", "n", "off", "disabled"}


def append_unique(target: list[str], value: str) -> None:
    if value and value not in target:
        target.append(value)


def scene_light_group(notes: str) -> str:
    for part in notes.replace("；", ";").split(";"):
        part = part.strip()
        if not part.startswith(SCENE_LIGHT_GROUP_PREFIX):
            continue
        group = part.removeprefix(SCENE_LIGHT_GROUP_PREFIX).strip()
        if group in SCENE_LIGHT_GROUPS:
            return group
    return ""


def build_data(sheets: dict[str, list[list[str]]]) -> dict[str, object]:
    data: dict[str, object] = {name: "" for name in CONSTANT_NAMES}
    for row in row_dicts(sheets.get("constants", [])):
        name = row.get("name", "")
        if name in CONSTANT_NAMES:
            data[name] = row.get("text", "")

    pools: dict[str, object] = {name: {} for name in POOL_NAMES}
    option_rows = row_dicts(sheets.get("options", []))
    option_rows.sort(key=lambda row: int(row.get("order") or 0) if (row.get("order") or "0").isdigit() else 0)
    for row in option_rows:
        if not enabled(row.get("enabled", "1")):
            continue
        pool = row.get("pool", "")
        text = row.get("text", "")
        scale = row.get("scale", "")
        shot = row.get("shot", "")
        if pool not in pools or not text:
            continue
        if pool in SCALE_SHOT_POOLS:
            if not scale or not shot:
                continue
            scale_map = pools[pool].setdefault(scale, {})
            if pool == "SCENE_LIGHT_OPTIONS":
                group = scene_light_group(row.get("notes", ""))
                if group:
                    existing = scale_map.get(shot)
                    if existing is None or isinstance(existing, list):
                        scale_map[shot] = {}
                    shot_map = scale_map[shot]
                    append_unique(shot_map.setdefault(group, []), text)
                    continue
                else:
                    # 无分组时，检查shot是否已有dict格式 -> 加入默认组
                    if isinstance(scale_map.get(shot), dict):
                        scale_map[shot].setdefault("default", [])
                        if text not in scale_map[shot]["default"]:
                            scale_map[shot]["default"].append(text)
                        continue
            append_unique(scale_map.setdefault(shot, []), text)
        elif pool in SHOT_POOLS:
            if not shot:
                continue
            append_unique(pools[pool].setdefault(shot, []), text)
        elif pool in SCALE_POOLS:
            if not scale:
                continue
            append_unique(pools[pool].setdefault(scale, []), text)
    data.update(pools)
    return data


def write_generated(path: Path, data: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "from __future__ import annotations",
        "",
        "# Generated by tools/build_prompt_data_from_excel.py.",
        "# Edit data/prompt_pools.xlsx, then rerun the build script.",
        "",
    ]
    for name in (*CONSTANT_NAMES, *POOL_NAMES):
        lines.append(f"{name} = {pprint.pformat(data.get(name), width=120, sort_dicts=False)}")
        lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Build runtime prompt data from the editable Excel workbook.")
    parser.add_argument("--input", default=str(DEFAULT_INPUT), help="Input .xlsx path.")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT), help="Generated Python output path.")
    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.is_absolute():
        input_path = ROOT / input_path
    output_path = Path(args.output)
    if not output_path.is_absolute():
        output_path = ROOT / output_path
    if not input_path.exists():
        raise FileNotFoundError(f"Excel source not found: {input_path}")
    data = build_data(read_workbook(input_path))
    write_generated(output_path, data)
    print(f"Wrote {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
