#!/bin/zsh

: "${RPP_COMFYUI_ROOT:=/Users/zouge/Documents/Codex/2026-06-02/macbook-air-80/work/ComfyUI}"
: "${RPP_PROXY_REMOTE_URL:=http://192.168.123.111:8188}"
: "${RPP_PROXY_LOCAL_MOBILE_URL:=http://127.0.0.1:8188}"
: "${RPP_PROXY_OUTPUT_DIR:=${RPP_COMFYUI_ROOT}/output/4090 生成}"
: "${RPP_PROXY_PORT:=18199}"
: "${RPP_PROXY_DELETE_REMOTE_OUTPUT:=1}"
: "${RPP_PROXY_WEBSOCKET_OUTPUT:=1}"
: "${RPP_PROXY_POLL_SECONDS:=1.5}"
: "${RPP_PROXY_HISTORY_TIMEOUT:=900}"

export RPP_COMFYUI_ROOT RPP_PROXY_REMOTE_URL RPP_PROXY_LOCAL_MOBILE_URL RPP_PROXY_OUTPUT_DIR
export RPP_PROXY_PORT RPP_PROXY_DELETE_REMOTE_OUTPUT RPP_PROXY_WEBSOCKET_OUTPUT
export RPP_PROXY_POLL_SECONDS RPP_PROXY_HISTORY_TIMEOUT
